repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        language: system
        types: [ python ]
      - id: isort
        name: isort
        entry: isort
        language: system
        types: [ python ]
        args: [
            '--line-length=110',
            '--trailing-comma',
            '--ensure-newline-before-comments',
            '--force-single-line-imports',
        ]
      - id: flake8
        name: flake8
        entry: flake8
        language: system
        types: [ python ]
