DATA_FOLDER: C:/Users/manue/Documents/kaggle_datasets/sentiment_labelled_sentences
FILES:
  AMAZON: amazon_cells_labelled.txt
  YELP: yelp_labelled.txt
  IMDB: imdb_labelled.txt

RESOURCES:
  RAW_DATASET: "sentiment_analysis/resources/raw_dataset.csv"
  TRAIN_INDEX: "sentiment_analysis/resources/train_index.csv"
  TEST_INDEX: "sentiment_analysis/resources/test_index.csv"
  VAL_INDEX: "sentiment_analysis/resources/val_index.csv"

RUN_ID: "95621e65bd89471ea6cf0f169aabdc47"
MLFLOW:
  EXPERIMENT_NAME: "sentiment_analysis"

HYPERPARAMETERS:
  RandomForestClassifier:
    n_estimators:
      min: 10
      max: 100
      type: int
      step: 10
    # criterion:
    #   options:
    #     - gini
    #     - entropy
    #     - log_loss
    #   type: str
    max_depth:
      min: 1
      max: 10
      type: int
      step: 1
    min_samples_split:
      min: 2
      max: 10
      type: int
      step: 1
    min_samples_leaf:
      min: 1
      max: 10
      type: int
      step: 1