DATA_FOLDER: C:/Users/manue/Documents/kaggle_datasets/sentiment_labelled_sentences
FILES:
  AMAZON: amazon_cells_labelled.txt
  YELP: yelp_labelled.txt
  IMDB: imdb_labelled.txt

RESOURCES:
  RAW_DATASET: "sentiment_analysis/resources/raw_dataset.csv"
  TRAIN_INDEX: "sentiment_analysis/resources/train_index.csv"
  TEST_INDEX: "sentiment_analysis/resources/test_index.csv"
  VAL_INDEX: "sentiment_analysis/resources/val_index.csv"